# Generated by Django 5.2.4 on 2025-08-03 23:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('software', 'Software'), ('fintech', 'FinTech'), ('healthcare', 'Healthcare'), ('energy', 'Energy'), ('education', 'Education'), ('retail', 'Retail'), ('logistics', 'Logistics'), ('cybersecurity', 'Cybersecurity'), ('ai_ml', 'AI/ML'), ('other', 'Other')], max_length=50)),
                ('revenue_range', models.CharField(choices=[('under_1m', 'Under $1M'), ('1_5m', '$1M - $5M'), ('5_20m', '$5M - $20M'), ('20_100m', '$20M - $100M'), ('100m_plus', '$100M+')], max_length=20)),
                ('funding_stage', models.CharField(choices=[('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('series_d', 'Series D'), ('ipo', 'IPO'), ('public', 'Public'), ('private', 'Private')], max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('founding_year', models.IntegerField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('embedding_vector', models.TextField(blank=True, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('equity', 'Equity Investment'), ('debt', 'Debt Investment'), ('acquisition', 'Acquisition'), ('merger', 'Merger'), ('partnership', 'Partnership')], max_length=20)),
                ('status', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('due_diligence', 'Due Diligence'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fit_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('analysis_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('investment_criteria', models.JSONField(default=dict)),
                ('target_industries', models.JSONField(default=list)),
                ('target_revenue_ranges', models.JSONField(default=list)),
                ('target_funding_stages', models.JSONField(default=list)),
                ('embedding_vector', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investment Theses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.investmentthesis'),
        ),
    ]
