# Generated by Django 5.2.4 on 2025-08-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentthesis',
            name='analysis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentthesis',
            name='confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='investmentthesis',
            name='extracted_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='investmentthesis',
            name='sentiment_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='investmentthesis',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentthesis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentthesis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investmentthesis',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
